# Generated by Django 5.0.2 on 2024-03-03 12:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="images/default.jpg",
                upload_to="profile_pics",
                validators=[account.models.validate_image_size],
            ),
        ),
    ]
