# Generated by Django 5.0.2 on 2024-03-03 13:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="images/default.jpg",
                null=True,
                upload_to="profile_pics",
                validators=[account.models.validate_image_size],
            ),
        ),
    ]
