# Generated by Django 5.0.2 on 2024-03-03 12:58

import item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default_artpic.jpg",
                null=True,
                upload_to="item_images",
                validators=[item.models.validate_image_size],
            ),
        ),
    ]
